import './modules/account'
import './modules/controls'
import './modules/footLogic'
import './modules/global'
import './modules/graphics'
import './modules/load'
import './modules/loaderModel'
import './modules/options'
import './modules/snakeLogic'

import './modules/test'
